from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(908, 477)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(255,255,255,1), stop:0.427447 rgba(57,164,214,1), stop:1 rgba(0,58,153,1));\n"
"")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 910, 480))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sales = QtWidgets.QWidget()
        self.tab_sales.setMouseTracking(True)
        self.tab_sales.setObjectName("tab_sales")
        self.label = QtWidgets.QLabel(self.tab_sales)
        self.label.setGeometry(QtCore.QRect(0, 10, 910, 330))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_sales, placeholderText='Скопируйте путь к папке с файлами')
        self.lineEdit.setGeometry(QtCore.QRect(10, 350, 880, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255); border-radius: 4px;")
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("textBrowser")
        self.saleButton = QtWidgets.QPushButton(self.tab_sales)
        self.saleButton.setGeometry(QtCore.QRect(370, 410, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saleButton.setFont(font)
        self.saleButton.setStyleSheet("background-color: rgb(0,58,153);\n"
"color: rgb(255, 255, 255);")
        self.saleButton.setObjectName("pushButton")

        self.salefoldButton = QtWidgets.QPushButton(self.tab_sales)
        self.salefoldButton.setGeometry(QtCore.QRect(75, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.salefoldButton.setFont(font)
        self.salefoldButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                      "color: rgb(255, 255, 255);")
        self.salefoldButton.setObjectName("foldButton")

        self.saleSaveButton = QtWidgets.QPushButton(self.tab_sales)
        self.saleSaveButton.setGeometry(QtCore.QRect(665, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saleSaveButton.setFont(font)
        self.saleSaveButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                          "color: rgb(255, 255, 255);")
        self.saleSaveButton.setObjectName("foldButton")

        self.tabWidget.addTab(self.tab_sales, "")
        self.tab_upa = QtWidgets.QWidget()
        self.tab_upa.setObjectName("tab_upa")
        self.unaButton = QtWidgets.QPushButton(self.tab_upa)
        self.unafoldButton = QtWidgets.QPushButton(self.tab_upa)
        self.unafoldButton.setGeometry(QtCore.QRect(75, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unafoldButton.setFont(font)
        self.unafoldButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                      "color: rgb(255, 255, 255);")
        self.unafoldButton.setObjectName("foldButton2")

        self.unaSaveButton = QtWidgets.QPushButton(self.tab_upa)
        self.unaSaveButton.setGeometry(QtCore.QRect(665, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unaSaveButton.setFont(font)
        self.unaSaveButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                          "color: rgb(255, 255, 255);")
        self.unaSaveButton.setObjectName("foldButton")

        self.unaButton.setGeometry(QtCore.QRect(370, 410, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unaButton.setFont(font)
        self.unaButton.setStyleSheet("background-color: rgb(0,58,153);\n"
"color: rgb(255, 255, 255);")
        self.unaButton.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_upa, placeholderText='Скопируйте путь к папке с файлами')
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 350, 880, 40))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(self.tab_upa)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 910, 330))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_upa, "")
        self.tab_162 = QtWidgets.QWidget()
        self.tab_162.setObjectName("tab_162")
        self.form162Button = QtWidgets.QPushButton(self.tab_162)
        self.form162Button.setGeometry(QtCore.QRect(370, 410, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.form162Button.setFont(font)
        self.form162Button.setStyleSheet("background-color: rgb(0,58,153);\n"
"color: rgb(255, 255, 255);")
        self.form162Button.setObjectName("pushButton_3")

        self.formfoldButton = QtWidgets.QPushButton(self.tab_162)
        self.formfoldButton.setGeometry(QtCore.QRect(75, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.formfoldButton.setFont(font)
        self.formfoldButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                          "color: rgb(255, 255, 255);")
        self.formfoldButton.setObjectName("foldButton")

        self.formSaveButton = QtWidgets.QPushButton(self.tab_162)
        self.formSaveButton.setGeometry(QtCore.QRect(665, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.formSaveButton.setFont(font)
        self.formSaveButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                         "color: rgb(255, 255, 255);")
        self.formSaveButton.setObjectName("foldButton")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_162, placeholderText='Скопируйте путь к папке с файлами')
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 350, 880, 40))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("textBrowser_3")
        self.label_3 = QtWidgets.QLabel(self.tab_162)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 910, 330))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_162, "")
        self.tab_court = QtWidgets.QWidget()
        self.tab_court.setObjectName("tab_court")
        self.courtButton = QtWidgets.QPushButton(self.tab_court)
        self.courtButton.setGeometry(QtCore.QRect(370, 410, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.courtButton.setFont(font)
        self.courtButton.setStyleSheet("background-color: rgb(0,58,153);\n"
"color: rgb(255, 255, 255);")
        self.courtButton.setObjectName("pushButton_4")

        self.courtfoldButton = QtWidgets.QPushButton(self.tab_court)
        self.courtfoldButton.setGeometry(QtCore.QRect(75, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.courtfoldButton.setFont(font)
        self.courtfoldButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                          "color: rgb(255, 255, 255);")
        self.courtfoldButton.setObjectName("foldButton")

        self.courtSaveButton = QtWidgets.QPushButton(self.tab_court)
        self.courtSaveButton.setGeometry(QtCore.QRect(665, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.courtSaveButton.setFont(font)
        self.courtSaveButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                          "color: rgb(255, 255, 255);")
        self.courtSaveButton.setObjectName("foldButton")

        self.label_4 = QtWidgets.QLabel(self.tab_court)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 910, 330))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_court, placeholderText='Скопируйте путь к папке с файлами')
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 350, 880, 40))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_court, "")
        self.tab_triangles = QtWidgets.QWidget()
        self.tab_triangles.setObjectName("tab_triangles")
        self.treButton = QtWidgets.QPushButton(self.tab_triangles)
        self.treButton.setGeometry(QtCore.QRect(370, 410, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treButton.setFont(font)
        self.treButton.setStyleSheet("background-color: rgb(0,58,153);\n"
"color: rgb(255, 255, 255);")
        self.treButton.setObjectName("pushButton_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_triangles, placeholderText='Скопируйте путь к папке с файлами')
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 350, 880, 40))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("textBrowser_5")
        self.label_5 = QtWidgets.QLabel(self.tab_triangles)
        self.trefoldButton = QtWidgets.QPushButton(self.tab_triangles)
        self.trefoldButton.setGeometry(QtCore.QRect(75, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trefoldButton.setFont(font)
        self.trefoldButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                      "color: rgb(255, 255, 255);")
        self.trefoldButton.setObjectName("foldButton5")

        self.treSaveButton = QtWidgets.QPushButton(self.tab_triangles)
        self.treSaveButton.setGeometry(QtCore.QRect(665, 410, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treSaveButton.setFont(font)
        self.treSaveButton.setStyleSheet("background-color: rgb(0,58,153);\n"
                                          "color: rgb(255, 255, 255);")
        self.treSaveButton.setObjectName("foldButton")

        self.label_5.setGeometry(QtCore.QRect(0, 10, 910, 330))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(False)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_triangles, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "InsuRep"))
        self.label.setText(_translate("MainWindow", " Разместите в папке следующие файлы:\n\n* еженедельный отчет\n* Казань\n* Краснодар\n* Москва\n* Набережные Челны\n* Нижний Новгород\n* Самара"))
        self.saleButton.setText(_translate("MainWindow", "Сформировать"))
        self.salefoldButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.saleSaveButton.setText(_translate("MainWindow", "Сохранить отчет"))
        self.courtfoldButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.formfoldButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.trefoldButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.unafoldButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sales), _translate("MainWindow", "Отчет по продажам"))
        self.unaButton.setText(_translate("MainWindow", "Сформировать"))
        self.unaSaveButton.setText(_translate("MainWindow", "Сохранить отчет"))
        self.formSaveButton.setText(_translate("MainWindow", "Сохранить отчет"))
        self.label_2.setText(_translate("MainWindow", " Разместите в папке следующие файлы:\n\n* Убыточность"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_upa), _translate("MainWindow", "Убыточность"))
        self.form162Button.setText(_translate("MainWindow", "Сформировать"))
        self.label_3.setText(_translate("MainWindow", " Разместите в папке следующие файлы:\n\n* Премии\n* Заключенные\n* Заявленные\n* Отказы\n* Убытки\n* Комиссионное вознаграждение\n* Перестрахование премии\n* Перестрахование убытки\n* Неустойки\n* ЗНУ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_162), _translate("MainWindow", "Форма 0420162"))
        self.courtButton.setText(_translate("MainWindow", "Сформировать"))
        self.courtSaveButton.setText(_translate("MainWindow", "Сохранить отчет"))
        self.label_4.setText(_translate("MainWindow", " Разместите в папке следующие файлы:\n\n* ВыплатыТрадиционные\n* ВыплатаПотерпевшимПВУ\n* Накладные расходы 71410\n* Накладные расходы 71418"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_court), _translate("MainWindow", "Судебная отчетность"))
        self.treButton.setText(_translate("MainWindow", "Сформировать"))
        self.treSaveButton.setText(_translate("MainWindow", "Сохранить отчет"))
        self.label_5.setText(_translate("MainWindow", " Разместите в папке следующие файлы:\n\n* Выплаты 2 плавающих года\n* Заявления 2 плавающих"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_triangles), _translate("MainWindow", "Треугольники убытков"))



